### ISSUE TITLE
Enhance Influxdb backend

### ISSUE THREAD

**Issue by dmehra** [juttle/juttle-influx-adapter#20]
Currently we only support InfluxDB 0.9, no auth. Plan to add:

- [x] Influx 0.8 support
- [x] Auth support

**Comment by bkutil** [comment]
We discussed the 0.8 support with @demmer and the conclusion was to only support versions from 0.9 onward, unless the older version is frequently used and/or there's a customer demand for it.

Auth support has been documented in #22.

@dmehra Is it OK to close this issue as resolved?

**Comment by bkutil** [comment]
Closing now as #22 was reviewed and merged.
