### ISSUE TITLE
measurements should be specified as a filter on `name`

### ISSUE THREAD

**Issue by demmer** [juttle/juttle-influx-adapter#34]
Currently when reading from influxdb, the user specifies the names of the metrics using the  `-measurements` option. These names end up in the data points using the field name `"measurement"`.

Although this is consistent with the terminology used by influxdb, it is inconsistent with the naming scheme for other adapters like graphite in which the name of the metric is identified using the field `"name"` and is actually conveyed as part of the filter expression in read and not as a separate option.

The influx adapter should use this same model for consistency and ease of use.

Specifically, this change would change

`read influx -db 'db' -measurements 'cpu' host='www'`
into
`read influx -db 'db' name='cpu' host='www'`

The resulting points would then have the name of the measurement in the "name" field.

To handle the case where the data happens to have a tag called `"name"` we would update the existing `-measurementField` option to be `-nameField` instead.

One nice benefit of this change is that the difference between exact string matching on the name vs regular expression matching on the name would be conveyed by whether the user specified == or ~= in the filter expression.

**Comment by dmehra** [comment]
+1

**Comment by bkutil** [comment]
> To handle the case where the data happens to have a tag called "name" we would update the existing -measurementField option to be -nameField instead.

Could you please provide an example incoming point, a Juttle query and the transformed point?

At the moment, what `measurementField` does during `read` is that it specifies into which field we will store the measurement name (default is none).

**Comment by bkutil** [comment]
The feature (except for the handling of aliasing mentioned in previous comment) is implemented in the referenced PR.

Couple of things I noticed:

- I think that `name` is really not a good choice. It is too generic - both for a filter key, point field and also as a name for the concept itself, and it can easily alias with a real tag. If possible, we should change to something more specific like `metric`.
- If we want to introduce this behaviour for all time-series adapters, it should be documented somewhere @dmehra - would you like to take care of that?

**Comment by demmer** [comment]
> Could you please provide an example incoming point, a Juttle read with options and the transformed point?

Sure. Assume one writes the following metric to influx:
```
cpu_user,host=server02 value=0.67 name=conflict
```

Running this juttle:
```
read influx -db "..." name='cpu_user'
```

Should result in the following point:
```
{ name: 'cpu_user', host: 'server02', value: 0.67 }
```

As well as a warning saying something like `Point(s) contained a "name" field -- use -nameField to make the field accessible.

On other other hand, this juttle:
```
read influx -db "..." -nameField "metric" metric='cpu_user'
```

Would result in the following point and no warning:
```
{ metric: 'cpu_user', host: 'server02', value: 0.67, name: 'conflict' }
```

Overall I'm assuming this case will be rare so I'm ok with not actually supporting it until / unless a user actually requests it. At that time we should probably add support for a `defaultNameField` option in the config so that users don't have to specify the `-nameField` option always in their juttles.

**Comment by bkutil** [comment]
Ok, I implemented this logic in the PR.
