### ISSUE TITLE
Add support for InfluxDB v0.10

### ISSUE THREAD

**Issue by dmehra** [juttle/juttle-influx-adapter#72]
v0.10 has arrived! https://docs.influxdata.com/influxdb/v0.10/concepts/09_vs_010/

@demmer would you agree that our adapters should generally support a single, most-recent version of the backend? In cases where we have active users of an earlier version, we'd consider continued support for it. Here it's not the case, other than cadvisor demo we have - not sure if it will "just work" with 0.10; maybe, given that differences from 0.9 are few.

**Comment by bkutil** [comment]
Looks like the current feature set of the adapter works just fine w/ 0.10.
